### ISSUE TITLE
KaitaiStream ( 'str' object has no attribute 'read')

### ISSUE THREAD

**Issue by ret5et** [kaitai-io/kaitai_struct_python_runtime#14]
According  this [documentation](http://formats.kaitai.io/bmp/python.html) we can use  KaitaiStream for reading data from stream. But ....

```

$ virtualenv  test
$ source test/bin/activate

$ pip2 install  kaitaistruct
....
Successfully installed kaitaistruct-0.7
$ pip2 install  enum34
...
Successfully installed enum34-1.1.6


$ ksc --version
kaitai-struct-compiler 0.7
$ ksc -t python  test.ksy
$ python2.7 testrun.py

Traceback (most recent call last):
  File "testrun.py", line 9, in <module>
    obj = Testparser(stream)
  File "<skip>/testparser.py", line 20, in __init__
    self.key_header = self._root.KeyHeader(self._io, self, self._root)
  File "<skip>/testparser.py", line 27, in __init__
    self.magic = self._io.ensure_fixed_contents(struct.pack('5b', 77, 65, 71, 73, 67))
  File "<skip>.local/lib/python2.7/site-packages/kaitaistruct.py", line 271, in ensure_fixed_contents
    actual = self._io.read(len(expected))
AttributeError: 'str' object has no attribute 'read'

```
```
$ cat test.ksy

meta:
  id: testparser
  endian: be
  encoding: ASCII

seq:
  - id: key_header
    type: key_header

types:
   key_header:
     seq:
       - id: magic
         contents: MAGIC
```
```
$ cat  testrun.py
__author__ = '@ret5et'

from kaitaistruct import KaitaiStream
from testparser import  Testparser

data =  "MAGIC\x00\x41\x41\x00"

stream = KaitaiStream(data)
obj = Testparser(stream)

```

**Comment by GreyCat** [comment]
Good catch, thanks, this documentation is indeed incorrect. The proper way to parse from a `bytes` (or a `str` in Python 2.7) is to wrap it into the BytesIO, and then use that IO for KaitaiStream:

```python
from kaitaistruct import KaitaiStream, BytesIO
from testparser import Testparser

data = b"MAGIC\x00\x41\x41\x00"

stream = KaitaiStream(BytesIO(data))
obj = Testparser(stream)
```

I'll try to fix that documentation ASAP. Thanks again!

**Comment by ret5et** [comment]
It does not work too.

```
   Testparser(BytesIO(data))
  File "<skip>", line 21, in __init__
    while not self._io.is_eof():
AttributeError: 'cStringIO.StringI' object has no attribute 'is_eof'

```

**Comment by GreyCat** [comment]
I believe it's not `Testparser(BytesIO(data))`, but `Testparser(KaitaiStream(BytesIO(data)))`.

**Comment by ret5et** [comment]
Now all is working! :D
Thanks!

**Comment by GreyCat** [comment]
Thanks for the bug report! I also thought that probably it would be nice to add more helper methods into KaitaiStruct, like `from_bytes` and `from_io`:

```python
data = b"MAGIC\x00\x41\x41\x00"
obj = Testparser.from_bytes(data)

io = some_socket.makefile()
obj = Testparser.from_io(io)
```

**Comment by arekbulski** [comment]
This thread is stale, should be closed.

**Comment by GreyCat** [comment]
Yeah, thanks.
