### ISSUE TITLE
io.UnsupportedOperation: read - When write stream to file with size-eos:true

### ISSUE THREAD

**Issue by critizero** [kaitai-io/kaitai_struct_python_runtime#75]
Hello, I was tring to use serialization feature to generate a bgp keepalive packet with python runtime. I defined a `size-eos: true` attribute, and tried to write the stream to a file. Then there is an Exception: io.UnsupportedOperation: read.
The ksy file:
```ksy
meta:
  id: bgp_packet
  title: BGP (Border Gateway Protocol) packet
  xref:
    rfc: 4271
  encoding: utf-8
  endian: be
seq:
  - id: marker
    size: 16
  - id: length
    type: u2
  - id: bgp_type
    type: u1
    enum: bgp_packet_type
  - id: body
    type:
      switch-on: bgp_type
      cases:
        "bgp_packet_type::open": open_msg
        "bgp_packet_type::update": update_msg
        "bgp_packet_type::notification": notification_msg
        "bgp_packet_type::keepalive": keepalive_msg
        "bgp_packet_type::route_refresh": routerefresh_msg
enums:
  bgp_packet_type:
    1: open
    2: update
    3: notification
    4: keepalive
    5: route_refresh
types:
  ...
  keepalive_msg:
    seq:
      - id: data
        size-eos: true
  ...
```
After `kaitai_struct_compiler/jvm/target/universal/stage/bin/kaitai-struct-compiler --read-write --no-auto-read -t python ./bgp_packet.ksy`, The py file:
```python
    ...
    class KeepaliveMsg(ReadWriteKaitaiStruct):
        def __init__(self, _io=None, _parent=None, _root=None):
            self._io = _io
            self._parent = _parent
            self._root = _root

        def _read(self):
            self.data = self._io.read_bytes_full()


        def _fetch_instances(self):
            pass


        def _write__seq(self, io=None):
            super(BgpPacket.KeepaliveMsg, self)._write__seq(io)
            self._io.write_bytes(self.data)
            if not self._io.is_eof():
                raise kaitaistruct.ConsistencyError(u"data", self._io.size() - self._io.pos(), 0)


        def _check(self):
            pass
    ...
```
My test:
```python
def test_write():
    np = BgpPacket()
    np.marker = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
    np.length = 19
    np.bgp_type = BgpPacket.BgpPacketType.keepalive
    kp = BgpPacket.KeepaliveMsg(None, np, np._root)
    kp.data = b''
    kp._check()
    np.body = kp
    np._check()

    nf = open('./new_bgp_packet.bin', 'wb')
    nf.truncate(19)

    with KaitaiStream(nf) as _io:
        np._write(_io)
```
I ran it and got exception:
```
Traceback (most recent call last):
  File "bgp_parser.py", line 53, in <module>
    test_write()
  File "bgp_parser.py", line 48, in test_write
    np._write(_io)
  File "kaitaistruct.py", line 64, in _write
    self._write__seq(io)
  File "bgp_packet.py", line 88, in _write__seq
    self.body._write__seq(self._io)
  File "bgp_packet.py", line 419, in _write__seq
    if not self._io.is_eof():
  File "kaitaistruct.py", line 110, in is_eof
    t = io.read(1)
io.UnsupportedOperation: read
```
In the function `_write__seq()`, there is a function self._io.is_eof(), the function is in the kaitaistruct.py:
https://github.com/kaitai-io/kaitai_struct_python_runtime/blob/master/kaitaistruct.py#L75-L85
In this function, it tries to `read` a byte and check if it is reaching an eof, but the stream was opened as 'wb'.
I changed the code as follow and it works:
```python
        # io = self._io
        # t = io.read(1)
        # if t == b'':
        #     return True
        if self.size() == self.pos():
            return True
```

**Comment by generalmimon** [comment]
Thanks @critizero, I'll fix this. Please continue to report issues/share suggestions as you come across them - it's very valuable to me.

**Comment by critizero** [comment]
Thanks for your reply.
And I made a mistake when I changing the code:
```python
        io = self._io
        # t = io.read(1)
        # if t == b'':
        #     return True
        if self.size() == self.pos():
            return True
```
The `io` will be use after this part, so it should not be commented out.
